// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi0dfbSCU0xCDBhWseIK51_b2Vl3C_1oc',
    appId: '1:199154685555:web:3ff3481d82c0edba8e7c06',
    messagingSenderId: '199154685555',
    projectId: 'handcod-e3e5b',
    authDomain: 'handcod-e3e5b.firebaseapp.com',
    storageBucket: 'handcod-e3e5b.firebasestorage.app',
    measurementId: 'G-BQ6QW0DKZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWQy9z-W5WmL69TzQXtOW_a2MkB1WxXsA',
    appId: '1:199154685555:android:d1ad1d944dccbc758e7c06',
    messagingSenderId: '199154685555',
    projectId: 'handcod-e3e5b',
    storageBucket: 'handcod-e3e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5nVomzYQr1pu8LLnnTxHLAW8I4ndSPI',
    appId: '1:199154685555:ios:9a2e99b7304022778e7c06',
    messagingSenderId: '199154685555',
    projectId: 'handcod-e3e5b',
    storageBucket: 'handcod-e3e5b.firebasestorage.app',
    iosClientId: '199154685555-cgr5b3iqpqgdigastgdvflcmooqs26bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.handcodeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5nVomzYQr1pu8LLnnTxHLAW8I4ndSPI',
    appId: '1:199154685555:ios:9a2e99b7304022778e7c06',
    messagingSenderId: '199154685555',
    projectId: 'handcod-e3e5b',
    storageBucket: 'handcod-e3e5b.firebasestorage.app',
    iosClientId: '199154685555-cgr5b3iqpqgdigastgdvflcmooqs26bd.apps.googleusercontent.com',
    iosBundleId: 'com.example.handcodeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi0dfbSCU0xCDBhWseIK51_b2Vl3C_1oc',
    appId: '1:199154685555:web:67ac4e80557146718e7c06',
    messagingSenderId: '199154685555',
    projectId: 'handcod-e3e5b',
    authDomain: 'handcod-e3e5b.firebaseapp.com',
    storageBucket: 'handcod-e3e5b.firebasestorage.app',
    measurementId: 'G-9QXJE0T7SN',
  );

}